Feature/#11 502 bug
recursion-backend-projects/E-Commerce-Chat-Microservice pull request #12
Opened 2024-06-18 14:25 UTC by seiichikick0404

## 概要

- nginxの502エラー修正

### Issue
#11 

## 目的
nginxの502エラーを修正するため

## やったこと
- コンテナ名を修正
- .envをsrc以下にも配置

## 確認方法
以下にアクセスしてNginxの502エラーが出てなければOK

https://chat.art-sa2.com/chat

無料枠を超えないようにチャットサーバーは定期的に停止させてます。
もし起動してない場合は声をかけてください。

## レビューで見てほしいこと、不安に思っていること
問題なく本番環境が動いているか

2024-06-18 15:13 UTC, Aki158 requested changes
実装ありがとうございます！
502エラー出ないこと確認しました。
レビューコメントしましたので、対応お願いします。

## レビュー
ステージング環境と本番環境で差が出るので、ステージング環境も同様に修正した方が、いいと思います。

2024-06-18 15:13 UTC, Aki158 commented on .github/workflows/cd-prod.yml
> +
`touch src/.env`で新たに環境ファイルを作成後に環境変数を追加されていますが、以下のように`touch .env`に追加したほうがいい気がします。

```
            cd ./E-Commerce-Chat-Microservice/src

            # 環境ファイルを作成する
            touch .env
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
            echo "PROD_RDS_USERNAME=${{ secrets.PROD_RDS_USERNAME }}" >> .env
            echo "PROD_RDS_PASSWORD=${{ secrets.PROD_RDS_PASSWORD }}" >> .env
            echo "PROD_RDS_HOSTNAME=${{ secrets.PROD_RDS_HOSTNAME }}" >> .env
            echo "PROD_RDS_DB_NAME=${{ secrets.PROD_RDS_DB_NAME }}" >> .env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env

            # Docker Hubから最新のイメージをプルしてコンテナを起動する
            cd ~/web/E-Commerce-Chat-Microservice
            sudo docker compose -f compose.prod.yml up -d --pull always
```

2024-06-19 01:32 UTC, seiichikick0404 commented on .github/workflows/cd-prod.yml
> +
プロジェクト直下の.envに環境変数を集約させました。確認お願いします。

2024-06-19 03:54 UTC, Aki158 commented on .github/workflows/cd-prod.yml
> +
実装ありがとうございます！
修正されていること確認できました。

2024-06-19 03:54 UTC, Aki158 approved these changes
修正お疲れ様でした。
承認しました。

2024-06-21 00:49 UTC, AkinoJoey reviewed
@seiichikick0404 
すみません！レビュー遅れました！
[こちらのジョブ](https://github.com/recursion-backend-projects/E-Commerce-Chat-Microservice/actions/runs/9565317356)を再実行しましたが、502エラーが出ている状況です！

2024-06-21 12:13 UTC, AkinoJoey approved these changes

2024-06-21 12:46 UTC, merged