Feature/#4 receive token
recursion-backend-projects/E-Commerce-Chat-Microservice pull request #7
Opened 2024-06-14 13:16 UTC by AkinoJoey

## 概要
websocket経由でトークンを受け取り、有効なトークンかどうか検証する

### Issue
https://github.com/recursion-backend-projects/E-Commerce-Chat-Microservice/issues/4

## 目的
チャット機能の実装の前準備として必要なため

## やったこと
-  golang-jwt, gorilla/websocket, godotenvモジュールを追加
-  /chatエンドポイントを作成
-  jwtを検証するauthenticate関数を作成
-  websocket検証のためのecho関数を作成

## 確認方法
[Rails側のプルリク](https://github.com/recursion-backend-projects/E-Commerce-Webapp-with-Stripe-Sync/pull/80)で確認お願いします！

## レビューで見てほしいこと、不安に思っていること
goサーバー側でトークンを受取、正常にデコードできるかどうか

2024-06-14 15:59 UTC, Aki158 commented on src/main.go
>  type Response struct {
Response構造体は、チャット機能と関係ないので削除して良いと思います。

2024-06-14 16:00 UTC, Aki158 commented on src/main.go
> +	Message string `json:"message"`
Response構造体は、チャット機能と関係ないので削除して良いと思います。

2024-06-14 16:01 UTC, Aki158 commented on src/main.go
> +	json.NewEncoder(w).Encode(response)
helloHandlerは、チャット機能と関係ないので削除して良いと思います。

2024-06-14 16:21 UTC, Aki158 requested changes
実装ありがとうございます！
goサーバー側でトークンを受取、正常にデコードできること確認できました。
レビューコメントをいくつか書いたので、対応お願いします。

## レビュー
main.goは、基本的には、main関数のみ記載するので、他の関数やグローバル変数は、別のファイルに記載してください。

Goでは、慣習として、pkgというディレクトリを作成し、その中で役割ごとにファイルを作成します。以下のような、ツリー構造をイメージしています。
```
src/
├── pkg/
│   ├── websocket/
│   │   ├── handler.go   → Echo関数を記載
│   │   ├── upgrader.go  → upgrader変数を記載
│   └── auth/
│      └── middleware.go → Authenticate関数を記載
├── go.sum
├── go.mod
└── main.go
```

2024-06-14 16:21 UTC, Aki158 commented on src/main.go
>  }
helloHandlerは、チャット機能と関係ないので削除して良いと思います。

2024-06-14 16:21 UTC, Aki158 commented on src/main.go
>  }
goodbyeHandlerは、チャット機能と関係ないので削除して良いと思います。

2024-06-14 16:21 UTC, Aki158 commented on src/main.go
> +	http.HandleFunc("/goodbye", goodbyeHandler)
チャット機能と関係ないので削除して良いと思います。

2024-06-14 16:21 UTC, Aki158 commented on src/main.go
> +	http.ListenAndServe(":8080", nil)
ポート番号のハードコーディングは良くないです。
.envに定義してください。

2024-06-14 16:21 UTC, Aki158 commented on src/main.go
> +	}
`log.Fatal`は、気軽に使用しないほうがいいです。

`log.Fatal` は、エラーメッセージを出力した後にプログラムを終了させるため、`godotenv.Load` がエラーを返すと、それ以降のコードは実行されず、HTTPサーバーも起動しません。これにより、フロントエンドに何も返さない状態になります。

2024-06-14 16:21 UTC, Aki158 commented on src/main.go
> +	c, err := upgrader.Upgrade(w, r, nil)
変数名がcだと、どのような変数かわかりません。
`conn`に修正してください。

2024-06-14 16:21 UTC, Aki158 commented on src/main.go
> +		mt, message, err := c.ReadMessage()
変数名がmtだと、どのような変数かわかりません。
`messageType`に修正してください。

2024-06-14 16:21 UTC, Aki158 commented on src/main.go
> +}
Response構造体は、チャット機能と関係ないので削除して良いと思います。

2024-06-14 16:21 UTC, Aki158 commented on src/main.go
> +	WriteBufferSize: 1024,
1024は、定数なのでconstで定義したほうがいいと思います。

2024-06-15 01:50 UTC, AkinoJoey commented
@Aki158 
ご確認ありがとうございます！すべて修正しました！

2024-06-15 03:00 UTC, seiichikick0404 approved these changes

2024-06-15 03:00 UTC, seiichikick0404 commented
goサーバー側でトークンを受取、正常にデコードできてることを確認できました！
私の方からは特に指摘ないので承認します。お疲れ様でした！

2024-06-15 03:52 UTC, Aki158 approved these changes
実装ありがとうございます！
全て問題ないこと確認できました。
お疲れ様でした🙇

2024-06-15 04:14 UTC, merged